name: orre_web
description: "원격 웨이팅, 원격 주문"
publish_to: 'none'
version: 1.0.5+6

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_flip_counter: ^0.3.4
  app_settings: ^5.1.1
  cached_network_image: ^3.3.1
  camera: ^0.10.6
  equatable: ^2.0.5
  hive: ^2.2.3
  path_provider: ^2.1.0
  # fast_cached_network_image: ^1.2.9
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_expandable_fab: ^2.0.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.1
  flutter_secure_storage: ^9.2.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: ^4.6.6
  go_router: ^14.1.2
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  image_picker: ^1.1.1
  internet_connectivity_checker: ^1.0.2
  liquid_pull_to_refresh: ^3.0.1
  location: ^6.0.2
  nfc_manager: ^3.4.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  qr_bar_code_scanner_dialog: ^0.0.5
  qr_code_dart_scan: ^0.8.0
  riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  simple_barcode_scanner: ^0.1.1
  sliver_app_bar_builder: ^1.1.0
  stomp_dart_client: ^2.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.6
  url_strategy: ^0.2.0
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/orre_logo.png
    - assets/images/loading_orre.gif
    - assets/images/waveform/orre_wave_shadow.svg
    - assets/images/waveform/orre_wave.svg

  fonts :
    - family: Dovemayo_gothic
      fonts :
        - asset : assets/fonts/Dovemayo_gothic.ttf