name: orre_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_flip_counter: ^0.3.4
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.1
  flutter_secure_storage: ^9.2.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: ^4.6.6
  go_router: ^14.1.2
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  internet_connectivity_checker: ^1.0.2
  location: ^6.0.2
  nfc_manager: ^3.4.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  shared_preferences: ^2.2.3
  sliver_app_bar_builder: ^1.1.0
  stomp_dart_client: ^2.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.6
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/orre_logo.png
    - assets/images/loading_orre.gif
    - assets/images/waveform/wave_shadow.png
    - assets/images/waveform/wave.png

  fonts :
    - family: Dovemayo_gothic
      fonts :
        - asset : assets/fonts/Dovemayo_gothic.ttf